spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates: 
            - Path=/auth/tutorials/**
            - Method=POST, PUT, DELETE
          filters:
            - TestFilter
        - id: auth-service_get
          uri: lb://auth-service
          predicates: 
            - Path=/auth/**
            - Method=GET, POST
        - id: tutorials-service
          uri: lb://tutorials-service
          predicates: 
            - Path=/api/**
            - Method=POST, PUT, DELETE
          filters:
            - TestFilter